### ISSUE TITLE
Multiple files attached to an object (Reverse one to many from examples)

### ISSUE THREAD

**Issue by mikeywaites** [dahlia/sqlalchemy-imageattach#19]
Lets say I have a Model `Event`.  An `Event` can have N attachments represented by `EventAttachment` model.  All the logic seems to be suited to the one case where there is a FK from `Event` to the file attachment stored on `EventAttachment`.  Obviously i could manage this manually but it seems all the logic for saving and working with files is wrapped up in the ImageSet query class.  Am i missing something here?

```
class Event(db.Model):
    __tablename__ =  "event"
   id = Column(Integer, primary_key=True)


class EventAttachment(db.Model, BaseMixin, Image):
    __tablename__ = 'event_attachment'

    id = Column(Integer, primary_key=True)
    event_id = Column(Integer, ForeignKey('event.id'), nullable=False)
```

Ideally i want to have N EventAttchement instances with the logic found in the ImageSet class.  Ie i can save multiple EventAttachments each with a file directly by doing something like

```
attachment = EventAttachment(event_id=1)
attachment.from_file(f)
```

Thanks.

**Comment by dahlia** [comment]
[Multiple image sets][1] have been supported since SQLAlchemy-ImageAttach 1.0.0 (which was released about a year ago), therefore I close this issue.

[1]: https://sqlalchemy-imageattach.readthedocs.io/en/1.1.0/guide/multiset.html
